# Site settings
title: Emerald | A simple Jekyll blog
description: "A minimal blog template, build with Jekyll."
url: "http://www.archietech.com"
author:
  name: "Archana singh"
  email: "hello@archietech.com"
  url: "http://www.archietech.com"

# Build settings
baseurl: /emerald/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

theme: jekyll-theme-minimal
